### ISSUE TITLE
third error 

### ISSUE THREAD

**Issue by hansputera** [Matix-Media/discord-alt-token-generator#12]
912:4936:0913/162858.499:ERROR:device_event_log_impl.cc(208)] [16:28:58.499] Bluetooth: bluetooth_adapter_winrt.cc:1074 Getting Default Adapter failed.
Traceback (most recent call last):
  File "generator.py", line 347, in <module>
    account = current_bot.generate_token()
  File "generator.py", line 57, in generate_token
    account = self.register_account()
  File "generator.py", line 147, in register_account
    next_button = self.driver.find_elements_by_css_selector(self.register_next_selector_us)[
IndexError: list index out of range

**Comment by nighttsss** [comment]
same

**Comment by hansputera** [comment]
lmao

**Comment by nighttsss** [comment]
hahaha any idea?

**Comment by hansputera** [comment]
fix by myself.

**Comment by nighttsss** [comment]
great idea, i got no idea..
