### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hateful911** [Matix-Media/discord-alt-token-generator#14]
Using: "python generator.py" = ERROR!
$ generator.py help
for more infos.

Using: "generator.py help" = nothing happens or pycharm opens to edit it

**Comment by ghost** [comment]
type python generator.py (number of accounts) (destop-name) 30 true (token-output) (invite codes when their alr made) (message link) Register delay:(sec per account)

**Comment by RavenKape** [comment]
> python generator.py (number of accounts) (destop-name) 30 true (token-output) (invite codes when their alr made) (message link) Register delay:(sec per account)

Traceback (most recent call last):
  File "generator.py", line 343, in <module>
    driver = webdriver.Chrome(options=options)
  File "C:\Python38\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot create default profile directory

**Comment by ghost** [comment]
try my code :https://pastebin.com/TrUxGNg7 (warning:this is is not the fully working but it should give you a clue on how its going to work)

`
then type on your powershell that's in the folder of generator.py : python generator.py 5 muzam 30 true tokenlist (YOUR INVITE CODE) discord.gg/(invite code) Register delay: 10
