### ISSUE TITLE
local variable terms_checkbox referenced before assignment

### ISSUE THREAD

**Issue by manofmanytalents** [Matix-Media/discord-alt-token-generator#4]
```
Register delay: 30
Tokens filename: tokens.txt
Invite link: discord.gg/******
Setup...

Starting loop...


DevTools listening on ws://127.0.0.1:49455/devtools/browser/737d24b1-ef59-4a9e-a58e-7702dffebcfa
Bot initialized
Traceback (most recent call last):
  File "C:\Users\*****\Downloads\stuff\Discord\a\a\generator.py", line 347, in <module>
    account = current_bot.generate_token()
  File "C:\Users\*****\Downloads\stuff\Discord\a\a\generator.py", line 57, in generate_token
    account = self.register_account()
  File "C:\Users\*****\Downloads\stuff\Discord\a\a\generator.py", line 153, in register_account
    terms_checkbox.click()
UnboundLocalError: local variable 'terms_checkbox' referenced before assignment
```

**Comment by Matix-Media** [comment]
Do you have the terms checkbox on the discord registration page?

**Comment by Matix-Media** [comment]
Yeah, found the error get fixed in the next update.
