### ISSUE TITLE
Getting error list index out of range

### ISSUE THREAD

**Issue by UjjwalD77** [Matix-Media/discord-alt-token-generator#9]
```

(venv) F:\Cool\Python THngs\discord-alt-token-generator>generator.py 10 devae 30 true tokensyoinked zbH6DR https://discord.gg/Ak63KE
Register delay: 30
Save userdata
Tokens filename: tokensyoinked.txt
Invite link: zbH6DE
Message channel URL: https://discord.gg/Ak33KE
Setup...

Starting loop...


DevTools listening on ws://127.0.0.1:60246/devtools/browser/960c0f40-7ec9-4da6-afba-287ae916f2aa
Bot initialized
Registering user: importedSardines9 Email: qGopU43qr4V@frontier.gov Password: jlfTo0NVPc
Traceback (most recent call last):
  File "F:\Cool\Python THngs\discord-alt-token-generator\generator.py", line 347, in <module>
    account = current_bot.generate_token()
  File "F:\Cool\Python THngs\discord-alt-token-generator\generator.py", line 57, in generate_token
    account = self.register_account()
  File "F:\Cool\Python THngs\discord-alt-token-generator\generator.py", line 148, in register_account
    0]
IndexError: list index out of range
```

Note: I have Latest version of chrome installed and the driver according to the Version.

**Comment by UjjwalD77** [comment]
Edit: i got it to work  still needs some editing but is working fine.

**Comment by DjarDjar** [comment]
> 
> 
> Edit: i got it to work still needs some editing but is working fine.

How?

**Comment by skriiizy** [comment]
same issue here care to explain how u fixed it ?

**Comment by Matix-Media** [comment]
Please create a pull request post your code snippet to help other people with the same issue.

**Comment by ghost** [comment]
> Please create a pull request post your code snippet to help other people with the same issue.

are you able to fix this by yourself?
